import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { useContext } from 'react';
import { Header, Hero, Modal, Row, Subscription } from 'src/components';
import { AuthContext } from 'src/context/auth.context';
import { IMovie } from 'src/interfaces/app.interface';
import { API_REQUEST } from 'src/services/api.service';
import { useInfoStore } from 'src/store';

export default function Home({
	trending,
	topRated,
	tvTopRated,
	popular,
	documentary,
	comedy,
	family,
	history,
}: HomeProps): JSX.Element {
	const { setModal, modal } = useInfoStore();
	const { isLoading } = useContext(AuthContext);
	const subscription = false;

	if (isLoading) return <>Loading...</>;
	if (!subscription) return <Subscription />;

	return (
		<div className='relative min-h-screen '>
			<Head>
				<title>Home - Nosirbek</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/logo.svg' />
			</Head>
			<Header />
			<main className='relative pl-4 pb-24 lg:space-y-24 lg:pl-16'>
				<Hero trending={trending} />
				<section>
					<Row movies={topRated} title='Top Rated' />
					<Row movies={tvTopRated} isBig={true} title='TV Show' />
					<Row movies={popular} title='Popular' />
					<Row movies={documentary} title='Documentary' isBig={true} />
					<Row movies={comedy} title='Comedy' />
					<Row movies={family} title='Family' isBig={true} />
					<Row movies={history} title='History' />
				</section>
			</main>
			{modal && <Modal />}
		</div>
	);
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
	const [trending, topRated, tvTopRated, popular, documentary, comedy, family, history] =
		await Promise.all([
			fetch(API_REQUEST.trending).then(res => res.json()),
			fetch(API_REQUEST.top_rated).then(res => res.json()),
			fetch(API_REQUEST.tv_top_rated).then(res => res.json()),
			fetch(API_REQUEST.popular).then(res => res.json()),
			fetch(API_REQUEST.documentary).then(res => res.json()),
			fetch(API_REQUEST.comedy).then(res => res.json()),
			fetch(API_REQUEST.family).then(res => res.json()),
			fetch(API_REQUEST.history).then(res => res.json()),
		]);

	return {
		props: {
			trending: trending.results,
			topRated: topRated.results,
			tvTopRated: tvTopRated.results,
			popular: popular.results,
			documentary: documentary.results,
			comedy: comedy.results,
			family: family.results,
			history: history.results,
		},
	};
};

interface HomeProps {
	trending: IMovie[];
	topRated: IMovie[];
	tvTopRated: IMovie[];
	popular: IMovie[];
	documentary: IMovie[];
	comedy: IMovie[];
	family: IMovie[];
	history: IMovie[];
}
