<<<<<<< HEAD
import { Inter } from '@next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Project</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
			</Head>
			<h1 className='text-3xl font-bold underline'>Hello world!</h1>
		</>
=======
import Head from 'next/head';
import { Header } from 'src/components';

export default function Home() {
	return (
		<div className='relative h-[200vh]'>
			<Head>
				<title>Home - Nossi</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/logo.svg' />
			</Head>
			<Header />
			<main>
				{/* Hero */}
				<section>
					{/* Row */}
					{/* BigRow */}
					{/* Row */}
					{/* BigRow */}
				</section>
			</main>
		</div>
>>>>>>> 4f4ef60 (header)
	);
}
